server:
  port: 8084

spring:
  resources:
    static-locations: classpath:/static/
logging:
  level:
    ROOT: warn
    org.example: debug

altair:
  mapping: /altair
  endpoint:
    graphql: /graphql
#    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: Altair
  cdn:
    enabled: true #TODO: move these resources to be local?!?
    version: 2.1.7
  props:
    resources:
      defaultQuery: defaultQuery.graphql
      variables: variables.graphql
#  headers:
#    Authorization: "Bearer <your-token>"